// packages/react-native/src/components/InfiniteList.tsx
import { useEffect, memo } from "react";
import { View, Text, TouchableOpacity } from "react-native";
import type { InfiniteListProps, Range } from "../types";
import { VirtualList } from "./VirtualList";
import { useInfinitePages, findMissingPages } from "@scrolloop/shared";

function InfiniteListInner<T>(props: InfiniteListProps<T>) {
  const {
    fetchPage,
    renderItem,
    itemSize,
    pageSize = 20,
    initialPage = 0,
    prefetchThreshold = 1,
    height = 400,
    overscan: userOverscan,
    style,
    renderLoading,
    renderError,
    renderEmpty,
    onPageLoad,
    onError,
    ...scrollViewProps
  } = props;

  const overscan = userOverscan ?? Math.max(20, pageSize * 2);

  const { allItems, pages, loadingPages, hasMore, error, loadPage, retry } =
    useInfinitePages({
      fetchPage,
      pageSize,
      initialPage,
      onPageLoad,
      onError,
    });

  useEffect(() => {
    if (pages.size === 0 && !error) {
      const totalNeededItems = Math.ceil(height / itemSize) + overscan * 2;
      for (
        let page = 0;
        page < Math.ceil(totalNeededItems / pageSize) + prefetchThreshold;
        page++
      )
        loadPage(page);
    }
  }, [
    pages.size,
    loadPage,
    initialPage,
    error,
    height,
    itemSize,
    pageSize,
    prefetchThreshold,
    overscan,
  ]);

  const handleRangeChange = (range: Range) => {
    const prefetchStart = Math.floor(range.startIndex / pageSize);
    const prefetchEnd =
      Math.floor(range.endIndex / pageSize) +
      prefetchThreshold +
      Math.ceil(overscan / pageSize);

    findMissingPages(prefetchStart, prefetchEnd, pages, loadingPages);

    for (let page = prefetchStart; page <= prefetchEnd; page++) {
      loadPage(page);
    }
  };

  if (error && allItems.length === 0) {
    if (renderError) {
      return (
        <View style={[{ height }, style]}>{renderError(error, retry)}</View>
      );
    }
    return (
      <View
        style={[
          {
            height,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          },
          style,
        ]}
      >
        <View style={{ alignItems: "center" }}>
          <Text>Error.</Text>
          <Text style={{ color: "#666", fontSize: 14, marginTop: 4 }}>
            {error.message}
          </Text>
          <TouchableOpacity
            onPress={retry}
            style={{ marginTop: 8, paddingVertical: 4, paddingHorizontal: 12 }}
          >
            <Text>Retry</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  if (allItems.length === 0 && loadingPages.size > 0) {
    if (renderLoading) {
      return <View style={[{ height }, style]}>{renderLoading()}</View>;
    }
    return (
      <View
        style={[
          {
            height,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          },
          style,
        ]}
      >
        <Text>Loading...</Text>
      </View>
    );
  }

  if (allItems.length === 0 && !hasMore) {
    if (renderEmpty) {
      return <View style={[{ height }, style]}>{renderEmpty()}</View>;
    }
    return (
      <View
        style={[
          {
            height,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          },
          style,
        ]}
      >
        <Text>No data.</Text>
      </View>
    );
  }

  return (
    <VirtualList
      {...scrollViewProps}
      count={allItems.length}
      itemSize={itemSize}
      height={height}
      overscan={overscan}
      style={style}
      onRangeChange={handleRangeChange}
      renderItem={(index, itemStyle) => {
        const item = allItems[index];
        return renderItem(item, index, itemStyle);
      }}
    />
  );
}

export const InfiniteList = memo(InfiniteListInner) as <T>(
  props: InfiniteListProps<T>
) => JSX.Element;

// packages/vue/src/components/InfiniteList.vue
<script setup lang="ts" generic="T">
import { computed, onMounted } from "vue";
import { findMissingPages } from "@scrolloop/shared";
import type { PageResponse, Range } from "@scrolloop/shared";
import VirtualList from "./VirtualList.vue";
import { useInfinitePages } from "../composables/useInfinitePages";

const props = withDefaults(
  defineProps<{
    fetchPage: (page: number, size: number) => Promise<PageResponse<T>>;
    itemSize: number;
    pageSize?: number;
    initialPage?: number;
    prefetchThreshold?: number;
    height?: number;
    overscan?: number;
    class?: string;
  }>(),
  {
    pageSize: 20,
    initialPage: 0,
    prefetchThreshold: 1,
    height: 400,
  }
);

const emit = defineEmits<{
  pageLoad: [page: number, items: T[]];
  error: [error: Error];
}>();

const overscan = computed(
  () => props.overscan ?? Math.max(20, props.pageSize * 2)
);

const { pages, loadingPages, allItems, hasMore, error, loadPage, retry } =
  useInfinitePages<T>({
    fetchPage: props.fetchPage,
    pageSize: props.pageSize,
    initialPage: props.initialPage,
    onPageLoad: (page, items) => emit("pageLoad", page, items),
    onError: (err) => emit("error", err),
  });

onMounted(() => {
  const needed = Math.ceil(props.height / props.itemSize) + overscan.value * 2;
  const count = Math.ceil(needed / props.pageSize) + props.prefetchThreshold;
  for (let p = 0; p < count; p++) loadPage(p);
});

function handleRangeChange(range: Range) {
  const ps = (range.startIndex / props.pageSize) | 0;
  const pe =
    ((range.endIndex / props.pageSize) | 0) +
    props.prefetchThreshold +
    Math.ceil(overscan.value / props.pageSize);
  findMissingPages(ps, pe, pages.value, loadingPages.value);
  for (let p = ps; p <= pe; p++) loadPage(p);
}
</script>

<template>
  <div :style="{ height: `${height}px` }">
    <template v-if="error && !allItems.length">
      <slot name="error" :error="error" :retry="retry">
        <div
          style="
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
          "
        >
          <div style="text-align: center">
            <p>Error: {{ error.message }}</p>
            <button @click="retry" style="margin-top: 8px; cursor: pointer">
              Retry
            </button>
          </div>
        </div>
      </slot>
    </template>

    <template v-else-if="!allItems.length && loadingPages.size">
      <slot name="loading">
        <div
          style="
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
          "
        >
          <p>Loading...</p>
        </div>
      </slot>
    </template>

    <template v-else-if="!allItems.length && !hasMore">
      <slot name="empty">
        <div
          style="
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
          "
        >
          <p>No data.</p>
        </div>
      </slot>
    </template>

    <VirtualList
      v-else
      :count="allItems.length"
      :item-size="itemSize"
      :height="height"
      :overscan="overscan"
      :class="$props.class"
      @range-change="handleRangeChange"
    >
      <template #default="{ index, style }">
        <slot :item="allItems[index]" :index="index" :style="style" />
      </template>
    </VirtualList>
  </div>
</template>
