// packages/svelte/src/VirtualList.svelte
<script lang="ts" generics="T">
  import { calculateVirtualRange } from "@scrolloop/core";
  import type { Snippet } from "svelte";

  interface Props {
    count: number;
    itemSize: number;
    height?: number;
    overscan?: number;
    onRangeChange?: (range: { startIndex: number; endIndex: number }) => void;
    children: Snippet<[index: number, style: Record<string, string>]>;
  }

  let {
    count,
    itemSize,
    height = 400,
    overscan = 4,
    onRangeChange,
    children,
  }: Props = $props();

  let containerEl: HTMLDivElement | undefined = $state();
  let scrollTop = $state(0);
  let prevScrollTop = $state(0);

  const totalHeight = $derived(count * itemSize);

  const range = $derived(
    calculateVirtualRange(scrollTop, height, itemSize, count, overscan, prevScrollTop)
  );

  const virtualItems = $derived.by(() => {
    const items: Array<{ index: number; style: Record<string, string> }> = [];
    for (let i = range.renderStart; i <= range.renderEnd; i++) {
      items.push({
        index: i,
        style: {
          position: "absolute",
          top: `${i * itemSize}px`,
          left: "0",
          right: "0",
          height: `${itemSize}px`,
        },
      });
    }
    return items;
  });

  $effect(() => {
    onRangeChange?.({ startIndex: range.renderStart, endIndex: range.renderEnd });
  });

  $effect(() => {
    const el = containerEl;
    if (!el) return;

    function handleScroll() {
      prevScrollTop = scrollTop;
      scrollTop = el.scrollTop;
    }

    el.addEventListener("scroll", handleScroll, { passive: true });
    return () => el.removeEventListener("scroll", handleScroll);
  });
</script>

<div
  bind:this={containerEl}
  role="list"
  style:overflow="auto"
  style:height="{height}px"
  style:position="relative"
>
  <div style:position="relative" style:height="{totalHeight}px" style:width="100%">
    {#each virtualItems as item (item.index)}
      <div role="listitem">
        {@render children(item.index, item.style)}
      </div>
    {/each}
  </div>
</div>

// packages/vue/src/components/VirtualList.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from "vue";
import { calculateVirtualRange } from "@scrolloop/core";
import type { Range } from "@scrolloop/shared";

const props = withDefaults(
  defineProps<{
    count: number;
    itemSize: number;
    height?: number;
    overscan?: number;
    class?: string;
  }>(),
  { height: 400, overscan: 4 }
);

const emit = defineEmits<{
  rangeChange: [range: Range];
}>();

const containerRef = ref<HTMLDivElement | null>(null);
const scrollTop = ref(0);
const prevScrollTop = ref(0);

const totalHeight = computed(() => props.count * props.itemSize);

const range = computed(() =>
  calculateVirtualRange(
    scrollTop.value,
    props.height,
    props.itemSize,
    props.count,
    props.overscan,
    prevScrollTop.value
  )
);

const virtualItems = computed(() => {
  const items: Array<{ index: number; style: Record<string, string> }> = [];
  for (let i = range.value.renderStart; i <= range.value.renderEnd; i++) {
    items.push({
      index: i,
      style: {
        position: "absolute",
        top: `${i * props.itemSize}px`,
        left: "0",
        right: "0",
        height: `${props.itemSize}px`,
      },
    });
  }
  return items;
});

watch(range, (r) => {
  emit("rangeChange", { startIndex: r.renderStart, endIndex: r.renderEnd });
});

function handleScroll() {
  const el = containerRef.value;
  if (!el) return;
  prevScrollTop.value = scrollTop.value;
  scrollTop.value = el.scrollTop;
}

onMounted(() => {
  containerRef.value?.addEventListener("scroll", handleScroll, {
    passive: true,
  });
});

onUnmounted(() => {
  containerRef.value?.removeEventListener("scroll", handleScroll);
});
</script>

<template>
  <div
    ref="containerRef"
    role="list"
    :class="$props.class"
    :style="{ overflow: 'auto', height: `${height}px` }"
  >
    <div
      :style="{
        position: 'relative',
        height: `${totalHeight}px`,
        width: '100%',
      }"
    >
      <template v-for="item in virtualItems" :key="item.index">
        <slot :index="item.index" :style="item.style" />
      </template>
    </div>
  </div>
</template>
