// packages/vue/src/components/InfiniteList.vue
<script setup lang="ts" generic="T">
import { computed, onMounted } from "vue";
import { findMissingPages } from "@scrolloop/shared";
import type { PageResponse, Range } from "@scrolloop/shared";
import VirtualList from "./VirtualList.vue";
import { useInfinitePages } from "../composables/useInfinitePages";

const props = withDefaults(
  defineProps<{
    fetchPage: (page: number, size: number) => Promise<PageResponse<T>>;
    itemSize: number;
    pageSize?: number;
    initialPage?: number;
    prefetchThreshold?: number;
    height?: number;
    overscan?: number;
    class?: string;
  }>(),
  {
    pageSize: 20,
    initialPage: 0,
    prefetchThreshold: 1,
    height: 400,
  }
);

const emit = defineEmits<{
  pageLoad: [page: number, items: T[]];
  error: [error: Error];
}>();

const overscan = computed(
  () => props.overscan ?? Math.max(20, props.pageSize * 2)
);

const { pages, loadingPages, total, hasMore, error, loadPage, retry } =
  useInfinitePages<T>({
    fetchPage: props.fetchPage,
    pageSize: props.pageSize,
    initialPage: props.initialPage,
    onPageLoad: (page, items) => emit("pageLoad", page, items),
    onError: (err) => emit("error", err),
  });

onMounted(() => {
  const needed = Math.ceil(props.height / props.itemSize) + overscan.value * 2;
  const count = Math.ceil(needed / props.pageSize) + props.prefetchThreshold;
  for (let p = 0; p < count; p++) loadPage(p);
});

function handleRangeChange(range: Range) {
  const ps = (range.startIndex / props.pageSize) | 0;
  const pe =
    ((range.endIndex / props.pageSize) | 0) +
    props.prefetchThreshold +
    Math.ceil(overscan.value / props.pageSize);
  findMissingPages(ps, pe, pages.value, loadingPages.value);
  for (let p = ps; p <= pe; p++) loadPage(p);
}
</script>

<template>
  <div :style="{ height: `${height}px` }">
    <template v-if="error && total === 0">
      <slot name="error" :error="error" :retry="retry">
        <div class="scrolloop-state-container">
          <div class="scrolloop-error-content">
            <p class="scrolloop-error-message">Error: {{ error.message }}</p>
            <button class="scrolloop-retry-button" @click="retry">Retry</button>
          </div>
        </div>
      </slot>
    </template>

    <template v-else-if="total === 0 && loadingPages.size">
      <slot name="loading">
        <div class="scrolloop-state-container">
          <p class="scrolloop-state-text">Loading...</p>
        </div>
      </slot>
    </template>

    <template v-else-if="total === 0 && !hasMore">
      <slot name="empty">
        <div class="scrolloop-state-container">
          <p class="scrolloop-state-text">No data.</p>
        </div>
      </slot>
    </template>

    <VirtualList
      v-else
      :count="total"
      :item-size="itemSize"
      :height="height"
      :overscan="overscan"
      :class="$props.class"
      @range-change="handleRangeChange"
    >
      <template #default="{ index, style }">
        <slot
          :item="pages.get(Math.floor(index / props.pageSize))?.[index % props.pageSize]"
          :index="index"
          :style="style"
        />
      </template>
    </VirtualList>
  </div>
</template>

<style>
.scrolloop-state-container {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.scrolloop-error-content {
  text-align: center;
}

.scrolloop-error-message {
  margin: 0 0 8px;
}

.scrolloop-retry-button {
  padding: 4px 12px;
  cursor: pointer;
}

.scrolloop-state-text {
  margin: 0;
}
</style>

// packages/preact/src/components/InfiniteList.tsx
import { useEffect, useCallback, useMemo } from "preact/hooks";
import type { CSSProperties } from "preact";
import type { InfiniteListProps } from "../types";
import { VirtualList } from "./VirtualList";
import { useInfinitePages } from "../hooks/useInfinitePages";
import "./infiniteList.css";

export function InfiniteList<T>({
  fetchPage,
  renderItem,
  itemSize,
  pageSize = 20,
  initialPage = 0,
  height = 400,
  overscan: userOverscan,
  class: className,
  style,
  renderLoading,
  renderError,
  renderEmpty,
  onPageLoad,
  onError,
}: InfiniteListProps<T>) {
  const overscan = useMemo(
    () => userOverscan ?? Math.max(20, pageSize * 2),
    [userOverscan, pageSize]
  );

  const { pages, total, loadingPages, hasMore, error, loadPage, retry } =
    useInfinitePages({ fetchPage, pageSize, initialPage, onPageLoad, onError });

  useEffect(() => {
    if (total === 0 && !error) {
      const needed = Math.ceil(height / itemSize) + overscan * 2;
      const pagesToLoad = Math.ceil(needed / pageSize);
      for (let p = 0; p < pagesToLoad; p++) loadPage(p);
    }
  }, [total, error, height, itemSize, pageSize, overscan, loadPage]);

  const handleRangeChange = useCallback(
    (range: { startIndex: number; endIndex: number }) => {
      const ps = (range.startIndex / pageSize) | 0;
      const pe = ((range.endIndex / pageSize) | 0) + 1;
      for (let p = ps; p <= pe; p++) loadPage(p);
    },
    [pageSize, loadPage]
  );

  const virtualRenderItem = useCallback(
    (index: number, itemStyle: CSSProperties) =>
      renderItem(
        pages.get(Math.floor(index / pageSize))?.[index % pageSize],
        index,
        itemStyle
      ),
    [pages, pageSize, renderItem]
  );

  if (error && total === 0) {
    if (renderError)
      return <div style={{ height }}>{renderError(error, retry)}</div>;
    return (
      <div class="scrolloop-state-container" style={{ height }}>
        <div class="scrolloop-error-content">
          <p class="scrolloop-error-message">Error.</p>
          <p class="scrolloop-error-detail">{error.message}</p>
          <button class="scrolloop-retry-button" onClick={retry}>
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (total === 0 && loadingPages.size > 0) {
    if (renderLoading) return <div style={{ height }}>{renderLoading()}</div>;
    return (
      <div class="scrolloop-state-container" style={{ height }}>
        <p class="scrolloop-state-text">Loading...</p>
      </div>
    );
  }

  if (total === 0 && !hasMore) {
    if (renderEmpty) return <div style={{ height }}>{renderEmpty()}</div>;
    return (
      <div class="scrolloop-state-container" style={{ height }}>
        <p class="scrolloop-state-text">No data.</p>
      </div>
    );
  }

  return (
    <VirtualList
      count={total}
      itemSize={itemSize}
      height={height}
      overscan={overscan}
      class={className}
      style={style}
      onRangeChange={handleRangeChange}
      renderItem={virtualRenderItem}
    />
  );
}
