// packages/svelte/src/VirtualList.svelte
<script lang="ts" generics="T">
  import { calculateVirtualRange } from "@scrolloop/core";
  import type { Snippet } from "svelte";

  interface Props {
    count: number;
    itemSize: number;
    height?: number;
    overscan?: number;
    onRangeChange?: (range: { startIndex: number; endIndex: number }) => void;
    children: Snippet<[index: number, style: Record<string, string>]>;
  }

  let {
    count,
    itemSize,
    height = 400,
    overscan = 4,
    onRangeChange,
    children,
  }: Props = $props();

  let containerEl: HTMLDivElement | undefined = $state();
  let scrollTop = $state(0);
  let prevScrollTop = $state(0);

  const totalHeight = $derived(count * itemSize);

  const range = $derived(
    calculateVirtualRange(scrollTop, height, itemSize, count, overscan, prevScrollTop)
  );

  const virtualItems = $derived.by(() => {
    const items: Array<{ index: number; style: Record<string, string> }> = [];
    for (let i = range.renderStart; i <= range.renderEnd; i++) {
      items.push({
        index: i,
        style: {
          position: "absolute",
          top: `${i * itemSize}px`,
          left: "0",
          right: "0",
          height: `${itemSize}px`,
        },
      });
    }
    return items;
  });

  $effect(() => {
    onRangeChange?.({ startIndex: range.renderStart, endIndex: range.renderEnd });
  });

  $effect(() => {
    const el = containerEl;
    if (!el) return;

    function handleScroll() {
      prevScrollTop = scrollTop;
      scrollTop = el.scrollTop;
    }

    el.addEventListener("scroll", handleScroll, { passive: true });
    return () => el.removeEventListener("scroll", handleScroll);
  });
</script>

<div
  bind:this={containerEl}
  role="list"
  style:overflow="auto"
  style:height="{height}px"
  style:position="relative"
>
  <div style:position="relative" style:height="{totalHeight}px" style:width="100%">
    {#each virtualItems as item (item.index)}
      <div role="listitem">
        {@render children(item.index, item.style)}
      </div>
    {/each}
  </div>
</div>

// packages/preact/src/components/VirtualList.tsx
import {
  useRef,
  useState,
  useEffect,
  useCallback,
  useMemo,
} from "preact/hooks";
import type { CSSProperties } from "preact";
import { calculateVirtualRange } from "@scrolloop/core";
import type { VirtualListProps } from "../types";

export function VirtualList({
  count,
  itemSize,
  renderItem,
  height = 400,
  overscan = 4,
  class: className,
  style,
  onRangeChange,
}: VirtualListProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const scrollTopRef = useRef(0);
  const prevScrollTopRef = useRef(0);
  const onRangeChangeRef = useRef(onRangeChange);
  const [, forceUpdate] = useState(0);
  const prevRangeRef = useRef({ start: -1, end: -1 });

  useEffect(() => {
    onRangeChangeRef.current = onRangeChange;
  }, [onRangeChange]);

  const totalHeight = count * itemSize;

  const { renderStart, renderEnd } = calculateVirtualRange(
    scrollTopRef.current,
    height,
    itemSize,
    count,
    overscan,
    prevScrollTopRef.current
  );

  useEffect(() => {
    const cb = onRangeChangeRef.current;
    if (
      cb &&
      (prevRangeRef.current.start !== renderStart ||
        prevRangeRef.current.end !== renderEnd)
    ) {
      prevRangeRef.current = { start: renderStart, end: renderEnd };
      cb({ startIndex: renderStart, endIndex: renderEnd });
    }
  }, [renderStart, renderEnd]);

  const handleScroll = useCallback(() => {
    const el = containerRef.current;
    if (!el) return;
    prevScrollTopRef.current = scrollTopRef.current;
    scrollTopRef.current = el.scrollTop;
    forceUpdate((n) => n + 1);
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    el.addEventListener("scroll", handleScroll, { passive: true });
    return () => el.removeEventListener("scroll", handleScroll);
  }, [handleScroll]);

  const items = useMemo(() => {
    const result = [];
    for (let i = renderStart; i <= renderEnd; i++) {
      const itemStyle: CSSProperties = {
        position: "absolute",
        top: i * itemSize,
        left: 0,
        right: 0,
        height: itemSize,
      };
      result.push(
        <div key={i} role="listitem">
          {renderItem(i, itemStyle)}
        </div>
      );
    }
    return result;
  }, [renderStart, renderEnd, itemSize, renderItem]);

  const containerStyle: CSSProperties = {
    overflow: "auto",
    height,
    ...style,
  };

  return (
    <div
      ref={containerRef}
      role="list"
      class={className}
      style={containerStyle}
    >
      <div style={{ position: "relative", height: totalHeight, width: "100%" }}>
        {items}
      </div>
    </div>
  );
}
